### ISSUE TITLE
Missing window buttons

### ISSUE THREAD

**Issue by ghost** [manaporkun/Automatic-LOD-Generator#1]
Hello, first a realy thanks for your work !

So, i have a problem after selected the fbx : 
- Missing window buttons
- Some errors

https://imgur.com/a/OYNwVyl

Thanks again for your work !

**Comment by manaporkun** [comment]
Hello,

Please check : https://github.com/manaporkun/Automatic-LOD-Generator#notes

**Comment by ghost** [comment]
Hi, i do exactly that :

1. added UnityMeshSimplifier from Unity Repository via the package manager.
2. added Automatic-LOD-Generator via the .unitypackage
3. tried with my fbx and suzanne

**Comment by manaporkun** [comment]
Could you please send me the detailed logs? I haven't tried on MacOS, that might cause some problems.

**Comment by ghost** [comment]
Sure! https://pastebin.com/JN7nNafT
Also, i'm on Linux.
